select
    cast(normal_high as {{ dbt.type_string() }}) as normal_high
  , cast(critical_low as {{ dbt.type_string() }}) as critical_low
  , cast(critical_high as {{ dbt.type_string() }}) as critical_high
  , cast(expiration_dt_tm as {{ dbt.type_timestamp() }}) as expiration_dt_tm
  , cast(event_tag_set_flag as {{ dbt.type_int() }}) as event_tag_set_flag
  , cast(note_importance_bit_map as {{ dbt.type_int() }}) as note_importance_bit_map
  , cast(clinsig_updt_dt_tm as {{ dbt.type_timestamp() }}) as clinsig_updt_dt_tm
  , cast(order_action_sequence as {{ dbt.type_int() }}) as order_action_sequence
  , cast(entry_mode_cd as {{ dbt.type_int() }}) as entry_mode_cd
  , cast(source_cd as {{ dbt.type_int() }}) as source_cd
  , cast(clinical_seq as {{ dbt.type_string() }}) as clinical_seq
  , cast(task_assay_version_nbr as {{ dbt.type_int() }}) as task_assay_version_nbr
  , cast(modifier_long_text_id as {{ dbt.type_int() }}) as modifier_long_text_id
  , cast(src_event_id as {{ dbt.type_int() }}) as src_event_id
  , cast(src_clinsig_updt_dt_tm as {{ dbt.type_timestamp() }}) as src_clinsig_updt_dt_tm
  , cast(nomen_string_flag as {{ dbt.type_int() }}) as nomen_string_flag
  , cast(ce_dynamic_label_id as {{ dbt.type_int() }}) as ce_dynamic_label_id
  , cast(last_utc_ts as {{ dbt.type_timestamp() }}) as last_utc_ts
  , cast(device_free_txt as {{ dbt.type_string() }}) as device_free_txt
  , cast(trait_bit_map as {{ dbt.type_int() }}) as trait_bit_map
  , cast(clinical_event_id as {{ dbt.type_int() }}) as clinical_event_id
  , cast(encntr_id as {{ dbt.type_int() }}) as encntr_id
  , cast(person_id as {{ dbt.type_int() }}) as person_id
  , cast(event_start_dt_tm as {{ dbt.type_timestamp() }}) as event_start_dt_tm
  , cast(encntr_financial_id as {{ dbt.type_int() }}) as encntr_financial_id
  , cast(event_id as {{ dbt.type_int() }}) as event_id
  , cast(valid_until_dt_tm as {{ dbt.type_timestamp() }}) as valid_until_dt_tm
  , cast(event_title_text as {{ dbt.type_string() }}) as event_title_text
  , cast(view_level as {{ dbt.type_int() }}) as view_level
  , cast(order_id as {{ dbt.type_int() }}) as order_id
  , cast(catalog_cd as {{ dbt.type_int() }}) as catalog_cd
  , cast(series_ref_nbr as {{ dbt.type_string() }}) as series_ref_nbr
  , cast(accession_nbr as {{ dbt.type_string() }}) as accession_nbr
  , cast(contributor_system_cd as {{ dbt.type_int() }}) as contributor_system_cd
  , cast(reference_nbr as {{ dbt.type_string() }}) as reference_nbr
  , cast(parent_event_id as {{ dbt.type_int() }}) as parent_event_id
  , cast(event_reltn_cd as {{ dbt.type_int() }}) as event_reltn_cd
  , cast(valid_from_dt_tm as {{ dbt.type_timestamp() }}) as valid_from_dt_tm
  , cast(event_class_cd as {{ dbt.type_int() }}) as event_class_cd
  , cast(event_cd as {{ dbt.type_int() }}) as event_cd
  , cast(event_tag as {{ dbt.type_string() }}) as event_tag
  , cast(event_end_dt_tm as {{ dbt.type_timestamp() }}) as event_end_dt_tm
  , cast(event_end_dt_tm_os as {{ dbt.type_int() }}) as event_end_dt_tm_os
  , cast(result_val as {{ dbt.type_string() }}) as result_val
  , cast(result_units_cd as {{ dbt.type_int() }}) as result_units_cd
  , cast(result_time_units_cd as {{ dbt.type_int() }}) as result_time_units_cd
  , cast(task_assay_cd as {{ dbt.type_int() }}) as task_assay_cd
  , cast(record_status_cd as {{ dbt.type_int() }}) as record_status_cd
  , cast(result_status_cd as {{ dbt.type_int() }}) as result_status_cd
  , cast(authentic_flag as {{ dbt.type_int() }}) as authentic_flag
  , cast(publish_flag as {{ dbt.type_int() }}) as publish_flag
  , cast(qc_review_cd as {{ dbt.type_int() }}) as qc_review_cd
  , cast(normalcy_cd as {{ dbt.type_int() }}) as normalcy_cd
  , cast(normalcy_method_cd as {{ dbt.type_int() }}) as normalcy_method_cd
  , cast(inquire_security_cd as {{ dbt.type_int() }}) as inquire_security_cd
  , cast(resource_group_cd as {{ dbt.type_int() }}) as resource_group_cd
  , cast(resource_cd as {{ dbt.type_int() }}) as resource_cd
  , cast(subtable_bit_map as {{ dbt.type_int() }}) as subtable_bit_map
  , cast(collating_seq as {{ dbt.type_string() }}) as collating_seq
  , cast(verified_dt_tm as {{ dbt.type_timestamp() }}) as verified_dt_tm
  , cast(verified_prsnl_id as {{ dbt.type_int() }}) as verified_prsnl_id
  , cast(performed_dt_tm as {{ dbt.type_timestamp() }}) as performed_dt_tm
  , cast(performed_prsnl_id as {{ dbt.type_int() }}) as performed_prsnl_id
  , cast(updt_dt_tm as {{ dbt.type_timestamp() }}) as updt_dt_tm
  , cast(updt_id as {{ dbt.type_int() }}) as updt_id
  , cast(updt_task as {{ dbt.type_int() }}) as updt_task
  , cast(updt_cnt as {{ dbt.type_int() }}) as updt_cnt
  , cast(updt_applctx as {{ dbt.type_int() }}) as updt_applctx
  , cast(normal_low as {{ dbt.type_string() }}) as normal_low
  , cast(event_end_tz_name as {{ dbt.type_string() }}) as event_end_tz_name
  , cast(event_start_tz_name as {{ dbt.type_string() }}) as event_start_tz_name
  , cast(performed_tz_name as {{ dbt.type_string() }}) as performed_tz_name
  , cast(verified_tz_name as {{ dbt.type_string() }}) as verified_tz_name
from {{ source('cerner_raw', 'clinical_event') }}
