select
    cast(active_status_dt_tm as {{ dbt.type_timestamp() }}) as active_status_dt_tm
    , cast(beg_effective_dt_tm as {{ dbt.type_timestamp() }}) as beg_effective_dt_tm
    , cast(end_effective_dt_tm as {{ dbt.type_timestamp() }}) as end_effective_dt_tm
    , cast(prim_cdm_desc as {{ dbt.type_string() }}) as prim_cdm_desc
    , cast(prim_cpt_desc as {{ dbt.type_string() }}) as prim_cpt_desc
    , cast(order_nbr as {{ dbt.type_string() }}) as order_nbr
    , cast(perf_phys_id as {{ dbt.type_int() }}) as perf_phys_id
    , cast(process_flg as {{ dbt.type_int() }}) as process_flg
    , cast(manual_ind as {{ dbt.type_int() }}) as manual_ind
    , cast(posted_dt_tm as {{ dbt.type_timestamp() }}) as posted_dt_tm
    , cast(diag_desc1 as {{ dbt.type_string() }}) as diag_desc1
    , cast(diag_desc2 as {{ dbt.type_string() }}) as diag_desc2
    , cast(diag_desc3 as {{ dbt.type_string() }}) as diag_desc3
    , cast(gross_price as {{ dbt.type_float() }}) as gross_price
    , cast(discount_amount as {{ dbt.type_float() }}) as discount_amount
    , cast(override_desc as {{ dbt.type_string() }}) as override_desc
    , cast(fin_nbr_type_flg as {{ dbt.type_int() }}) as fin_nbr_type_flg
    , cast(admit_type_cd as {{ dbt.type_int() }}) as admit_type_cd
    , cast(med_service_cd as {{ dbt.type_int() }}) as med_service_cd
    , cast(activity_type_cd as {{ dbt.type_int() }}) as activity_type_cd
    , cast(perf_loc_cd as {{ dbt.type_int() }}) as perf_loc_cd
    , cast(prim_icd9_proc as {{ dbt.type_string() }}) as prim_icd9_proc
    , cast(prim_icd9_proc_desc as {{ dbt.type_string() }}) as prim_icd9_proc_desc
    , cast(cost_center_cd as {{ dbt.type_int() }}) as cost_center_cd
    , cast(bill_code_type_cdf as {{ dbt.type_string() }}) as bill_code_type_cdf
    , cast(code_modifier1_cd as {{ dbt.type_int() }}) as code_modifier1_cd
    , cast(code_modifier2_cd as {{ dbt.type_int() }}) as code_modifier2_cd
    , cast(code_modifier3_cd as {{ dbt.type_int() }}) as code_modifier3_cd
    , cast(code_modifier_more_ind as {{ dbt.type_int() }}) as code_modifier_more_ind
    , cast(bill_code_more_ind as {{ dbt.type_int() }}) as bill_code_more_ind
    , cast(diag_more_ind as {{ dbt.type_int() }}) as diag_more_ind
    , cast(icd9_proc_more_ind as {{ dbt.type_int() }}) as icd9_proc_more_ind
    , cast(abn_status_cd as {{ dbt.type_int() }}) as abn_status_cd
    , cast(user_def_ind as {{ dbt.type_int() }}) as user_def_ind
    , cast(charge_description as {{ dbt.type_string() }}) as charge_description
    , cast(verify_phys_id as {{ dbt.type_int() }}) as verify_phys_id
    , cast(code_revenue_cd as {{ dbt.type_int() }}) as code_revenue_cd
    , cast(code_revenue_more_ind as {{ dbt.type_int() }}) as code_revenue_more_ind
    , cast(qty_conv_factor as {{ dbt.type_float() }}) as qty_conv_factor
    , cast(ext_bill_qty as {{ dbt.type_int() }}) as ext_bill_qty
    , cast(ndc_ident as {{ dbt.type_string() }}) as ndc_ident
    , cast(interface_charge_id as {{ dbt.type_int() }}) as interface_charge_id
    , cast(order_dept as {{ dbt.type_int() }}) as order_dept
    , cast(interface_file_id as {{ dbt.type_int() }}) as interface_file_id
    , cast(charge_item_id as {{ dbt.type_int() }}) as charge_item_id
    , cast(batch_num as {{ dbt.type_int() }}) as batch_num
    , cast(bill_code1 as {{ dbt.type_string() }}) as bill_code1
    , cast(bill_code1_desc as {{ dbt.type_string() }}) as bill_code1_desc
    , cast(bill_code2 as {{ dbt.type_string() }}) as bill_code2
    , cast(bill_code2_desc as {{ dbt.type_string() }}) as bill_code2_desc
    , cast(bill_code3 as {{ dbt.type_string() }}) as bill_code3
    , cast(bill_code3_desc as {{ dbt.type_string() }}) as bill_code3_desc
    , cast(prim_cdm as {{ dbt.type_string() }}) as prim_cdm
    , cast(prim_cpt as {{ dbt.type_string() }}) as prim_cpt
    , cast(diag_code1 as {{ dbt.type_string() }}) as diag_code1
    , cast(diag_code2 as {{ dbt.type_string() }}) as diag_code2
    , cast(diag_code3 as {{ dbt.type_string() }}) as diag_code3
    , cast(person_name as {{ dbt.type_string() }}) as person_name
    , cast(person_id as {{ dbt.type_int() }}) as person_id
    , cast(encntr_id as {{ dbt.type_int() }}) as encntr_id
    , cast(fin_nbr as {{ dbt.type_string() }}) as fin_nbr
    , cast(med_nbr as {{ dbt.type_string() }}) as med_nbr
    , cast(service_dt_tm as {{ dbt.type_timestamp() }}) as service_dt_tm
    , cast(section_cd as {{ dbt.type_int() }}) as section_cd
    , cast(encntr_type_cd as {{ dbt.type_int() }}) as encntr_type_cd
    , cast(payor_id as {{ dbt.type_int() }}) as payor_id
    , cast(quantity as {{ dbt.type_float() }}) as quantity
    , cast(price as {{ dbt.type_float() }}) as price
    , cast(net_ext_price as {{ dbt.type_float() }}) as net_ext_price
    , cast(organization_id as {{ dbt.type_int() }}) as organization_id
    , cast(institution_cd as {{ dbt.type_int() }}) as institution_cd
    , cast(department_cd as {{ dbt.type_int() }}) as department_cd
    , cast(subsection_cd as {{ dbt.type_int() }}) as subsection_cd
    , cast(level5_cd as {{ dbt.type_int() }}) as level5_cd
    , cast(facility_cd as {{ dbt.type_int() }}) as facility_cd
    , cast(building_cd as {{ dbt.type_int() }}) as building_cd
    , cast(nurse_unit_cd as {{ dbt.type_int() }}) as nurse_unit_cd
    , cast(room_cd as {{ dbt.type_int() }}) as room_cd
    , cast(bed_cd as {{ dbt.type_int() }}) as bed_cd
    , cast(referring_phys_id as {{ dbt.type_int() }}) as referring_phys_id
    , cast(ord_phys_id as {{ dbt.type_int() }}) as ord_phys_id
    , cast(ord_doc_nbr as {{ dbt.type_string() }}) as ord_doc_nbr
    , cast(adm_phys_id as {{ dbt.type_int() }}) as adm_phys_id
    , cast(attending_phys_id as {{ dbt.type_int() }}) as attending_phys_id
    , cast(additional_encntr_phys1_id as {{ dbt.type_int() }}) as additional_encntr_phys1_id
    , cast(additional_encntr_phys2_id as {{ dbt.type_int() }}) as additional_encntr_phys2_id
    , cast(additional_encntr_phys3_id as {{ dbt.type_int() }}) as additional_encntr_phys3_id
    , cast(charge_type_cd as {{ dbt.type_int() }}) as charge_type_cd
    , cast(updt_cnt as {{ dbt.type_int() }}) as updt_cnt
    , cast(updt_dt_tm as {{ dbt.type_timestamp() }}) as updt_dt_tm
    , cast(updt_id as {{ dbt.type_int() }}) as updt_id
    , cast(updt_task as {{ dbt.type_int() }}) as updt_task
    , cast(updt_applctx as {{ dbt.type_int() }}) as updt_applctx
    , cast(active_ind as {{ dbt.type_int() }}) as active_ind
    , cast(active_status_cd as {{ dbt.type_int() }}) as active_status_cd
    , cast(active_status_prsnl_id as {{ dbt.type_int() }}) as active_status_prsnl_id
from {{ source('cerner_raw', 'interface_charge') }}
