select
    cast(assign_to_loc_dt_tm as {{ dbt.type_timestamp() }}) as assign_to_loc_dt_tm
  , cast(program_service_cd as {{ dbt.type_int() }}) as program_service_cd
  , cast(specialty_unit_cd as {{ dbt.type_int() }}) as specialty_unit_cd
  , cast(mental_health_dt_tm as {{ dbt.type_timestamp() }}) as mental_health_dt_tm
  , cast(mental_health_cd as {{ dbt.type_int() }}) as mental_health_cd
  , cast(doc_rcvd_dt_tm as {{ dbt.type_timestamp() }}) as doc_rcvd_dt_tm
  , cast(referral_rcvd_dt_tm as {{ dbt.type_timestamp() }}) as referral_rcvd_dt_tm
  , cast(alt_lvl_care_dt_tm as {{ dbt.type_timestamp() }}) as alt_lvl_care_dt_tm
  , cast(alc_decomp_dt_tm as {{ dbt.type_timestamp() }}) as alc_decomp_dt_tm
  , cast(region_cd as {{ dbt.type_int() }}) as region_cd
  , cast(sitter_required_cd as {{ dbt.type_int() }}) as sitter_required_cd
  , cast(alc_reason_cd as {{ dbt.type_int() }}) as alc_reason_cd
  , cast(placement_auth_prsnl_id as {{ dbt.type_int() }}) as placement_auth_prsnl_id
  , cast(patient_classification_cd as {{ dbt.type_int() }}) as patient_classification_cd
  , cast(mental_category_cd as {{ dbt.type_int() }}) as mental_category_cd
  , cast(psychiatric_status_cd as {{ dbt.type_int() }}) as psychiatric_status_cd
  , cast(inpatient_admit_dt_tm as {{ dbt.type_timestamp() }}) as inpatient_admit_dt_tm
  , cast(result_accumulation_dt_tm as {{ dbt.type_timestamp() }}) as result_accumulation_dt_tm
  , cast(pregnancy_status_cd as {{ dbt.type_int() }}) as pregnancy_status_cd
  , cast(initial_contact_dt_tm as {{ dbt.type_timestamp() }}) as initial_contact_dt_tm
  , cast(expected_delivery_dt_tm as {{ dbt.type_timestamp() }}) as expected_delivery_dt_tm
  , cast(onset_dt_tm as {{ dbt.type_timestamp() }}) as onset_dt_tm
  , cast(last_menstrual_period_dt_tm as {{ dbt.type_timestamp() }}) as last_menstrual_period_dt_tm
  , cast(level_of_service_cd as {{ dbt.type_int() }}) as level_of_service_cd
  , cast(abn_status_cd as {{ dbt.type_int() }}) as abn_status_cd
  , cast(est_financial_resp_amt as {{ dbt.type_float() }}) as est_financial_resp_amt
  , cast(preadmit_testing_cd as {{ dbt.type_int() }}) as preadmit_testing_cd
  , cast(readmit_cd as {{ dbt.type_int() }}) as readmit_cd
  , cast(accommodation_cd as {{ dbt.type_int() }}) as accomodation_cd
  , cast(accommodation_request_cd as {{ dbt.type_int() }}) as accommodation_request_cd
  , cast(alt_result_dest_cd as {{ dbt.type_int() }}) as alt_result_dest_cd
  , cast(ambulatory_cond_cd as {{ dbt.type_int() }}) as ambulatory_cond_cd
  , cast(courtesy_cd as {{ dbt.type_int() }}) as courtesy_cd
  , cast(diet_type_cd as {{ dbt.type_int() }}) as diet_type_cd
  , cast(isolation_cd as {{ dbt.type_int() }}) as isolation_cd
  , cast(med_service_cd as {{ dbt.type_int() }}) as med_service_cd
  , cast(result_dest_cd as {{ dbt.type_int() }}) as result_dest_cd
  , cast(confid_level_cd as {{ dbt.type_int() }}) as confid_level_cd
  , cast(vip_cd as {{ dbt.type_int() }}) as vip_cd
  , cast(name_last_key as {{ dbt.type_string() }}) as name_last_key
  , cast(name_first_key as {{ dbt.type_string() }}) as name_first_key
  , cast(name_full_formatted as {{ dbt.type_string() }}) as name_full_formatted
  , cast(name_last as {{ dbt.type_string() }}) as name_last
  , cast(name_first	as {{ dbt.type_string() }})  as name_first
  , cast(name_phonetic as {{ dbt.type_string() }}) as name_phonetic
  , cast(sex_cd as {{ dbt.type_int() }}) as sex_cd
  , cast(birth_dt_cd as {{ dbt.type_int() }}) as birth_dt_cd
  , cast(birth_dt_tm as {{ dbt.type_timestamp() }}) as birth_dt_tm
  , cast(species_cd as {{ dbt.type_int() }}) as species_cd
  , cast(data_status_cd as {{ dbt.type_int() }}) as data_status_cd
  , cast(data_status_dt_tm as {{ dbt.type_timestamp() }}) as data_status_dt_tm
  , cast(data_status_prsnl_id as {{ dbt.type_int() }}) as data_status_prsnl_id
  , cast(contributor_system_cd as {{ dbt.type_int() }}) as contributor_system_cd
  , cast(location_cd as {{ dbt.type_int() }}) as location_cd
  , cast(loc_facility_cd as {{ dbt.type_int() }}) as loc_facility_cd
  , cast(loc_building_cd as {{ dbt.type_int() }}) as loc_building_cd
  , cast(loc_nurse_unit_cd as {{ dbt.type_int() }}) as loc_nurse_unit_cd
  , cast(loc_room_cd as {{ dbt.type_int() }}) as loc_room_cd
  , cast(loc_bed_cd as {{ dbt.type_int() }}) as loc_bed_cd
  , cast(disch_dt_tm as {{ dbt.type_timestamp() }}) as disch_dt_tm
  , cast(guarantor_type_cd as {{ dbt.type_int() }}) as guarantor_type_cd
  , cast(loc_temp_cd as {{ dbt.type_int() }}) as loc_temp_cd
  , cast(organization_id as {{ dbt.type_int() }}) as organization_id
  , cast(reason_for_visit as {{ dbt.type_string() }}) as reason_for_visit
  , cast(encntr_financial_id as {{ dbt.type_int() }}) as encntr_financial_id
  , cast(name_first_synonym_id as {{ dbt.type_int() }}) as name_first_synonym_id
  , cast(financial_class_cd as {{ dbt.type_int() }}) as financial_class_cd
  , cast(bbd_procedure_cd as {{ dbt.type_int() }}) as bbd_procedure_cd
  , cast(info_given_by as {{ dbt.type_string() }}) as info_given_by
  , cast(safekeeping_cd as {{ dbt.type_int() }}) as safekeeping_cd
  , cast(trauma_cd as {{ dbt.type_int() }}) as trauma_cd
  , cast(triage_cd as {{ dbt.type_int() }}) as triage_cd
  , cast(triage_dt_tm as {{ dbt.type_timestamp() }}) as triage_dt_tm
  , cast(visitor_status_cd as {{ dbt.type_int() }}) as visitor_status_cd
  , cast(valuables_cd as {{ dbt.type_int() }}) as valuables_cd
  , cast(security_access_cd as {{ dbt.type_int() }}) as security_access_cd
  , cast(refer_facility_cd as {{ dbt.type_int() }}) as refer_facility_cd
  , cast(trauma_dt_tm as {{ dbt.type_timestamp() }}) as trauma_dt_tm
  , cast(accomp_by_cd as {{ dbt.type_int() }}) as accomp_by_cd
  , cast(accommodation_reason_cd as {{ dbt.type_int() }}) as accommodation_reason_cd
  , cast(chart_complete_dt_tm as {{ dbt.type_timestamp() }}) as chart_complete_dt_tm
  , cast(zero_balance_dt_tm as {{ dbt.type_timestamp() }}) as zero_balance_dt_tm
  , cast(archive_dt_tm as {{ dbt.type_timestamp() }}) as archive_dt_tm
  , cast(archive_dt_tm_act as {{ dbt.type_timestamp() }}) as archive_dt_tm_act
  , cast(purge_dt_tm_act as {{ dbt.type_timestamp() }}) as purge_dt_tm_act_act
  , cast(purge_dt_tm_est as {{ dbt.type_timestamp() }}) as purge_dt_tm_act_est
  , cast(encntr_complete_dt_tm as {{ dbt.type_timestamp() }}) as encntr_complete_dt_tm
  , cast(pa_current_status_cd as {{ dbt.type_int() }}) as pa_current_status_cd
  , cast(pa_current_status_dt_tm as {{ dbt.type_timestamp() }}) as pa_current_status_dt_tm
  , cast(parent_ret_criteria_id as {{ dbt.type_int() }}) as parent_ret_criteria_id
  , cast(service_category_cd as {{ dbt.type_int() }}) as service_category_cd
  , cast(contract_status_cd as {{ dbt.type_int() }}) as contract_status_cd
  , cast(est_length_of_stay	as {{ dbt.type_int() }}) as est_length_of_stay
  , cast(alt_lvl_care_cd as {{ dbt.type_int() }}) as alt_lvl_care_cd
  , cast(encntr_id as {{ dbt.type_int() }}) as encntr_id
  , cast(person_id as {{ dbt.type_int() }}) as person_id
  , cast(updt_cnt as {{ dbt.type_int() }}) as updt_cnt
  , cast(updt_dt_tm as {{ dbt.type_timestamp() }}) as updt_dt_tm
  , cast(updt_id as {{ dbt.type_int() }}) as updt_id
  , cast(updt_task as {{ dbt.type_int() }}) as updt_task
  , cast(updt_applctx as {{ dbt.type_int() }}) as updt_applctx
  , cast(active_ind as {{ dbt.type_int() }}) as active_ind
  , cast(active_status_cd as {{ dbt.type_int() }}) as active_status_cd
  , cast(active_status_dt_tm as {{ dbt.type_timestamp() }}) as active_status_dt_tm
  , cast(active_status_prsnl_id as {{ dbt.type_int() }}) as active_status_prsnl_id
  , cast(create_dt_tm as {{ dbt.type_timestamp() }}) as create_dt_tm
  , cast(create_prsnl_id as {{ dbt.type_int() }}) as create_prsnl_id
  , cast(beg_effective_dt_tm as {{ dbt.type_timestamp() }}) as beg_effective_dt_tm
  , cast(end_effective_dt_tm as {{ dbt.type_timestamp() }}) as end_effective_dt_tm
  , cast(encntr_class_cd as {{ dbt.type_int() }}) as encntr_class_cd
  , cast(encntr_type_cd as {{ dbt.type_int() }}) as encntr_type_cd
  , cast(encntr_type_class_cd as {{ dbt.type_int() }}) as encntr_type_class_cd
  , cast(encntr_status_cd as {{ dbt.type_int() }}) as encntr_status_cd
  , cast(pre_reg_dt_tm as {{ dbt.type_timestamp() }}) as pre_reg_dt_tm
  , cast(pre_reg_prsnl_id as {{ dbt.type_int() }}) as pre_reg_prsnl_id
  , cast(reg_dt_tm as {{ dbt.type_timestamp() }}) as reg_dt_tm
  , cast(reg_prsnl_id as {{ dbt.type_int() }}) as reg_prsnl_id
  , cast(est_arrive_dt_tm as {{ dbt.type_timestamp() }}) as est_arrive_dt_tm
  , cast(est_depart_dt_tm as {{ dbt.type_timestamp() }}) as est_depart_dt_tm
  , cast(arrive_dt_tm as {{ dbt.type_timestamp() }}) as arrive_dt_tm
  , cast(depart_dt_tm as {{ dbt.type_timestamp() }}) as depart_dt_tm
  , cast(admit_type_cd as {{ dbt.type_int() }})	as admit_type_cd
  , cast(admit_src_cd as {{ dbt.type_int() }}) as admit_src_cd
  , cast(admit_mode_cd as {{ dbt.type_int() }}) as admit_mode_cd
  , cast(admit_with_medication_cd as {{ dbt.type_int() }}) as admit_with_medication_cd
  , cast(referring_comment	as {{ dbt.type_string() }}) as referring_comment
  , cast(disch_disposition_cd as {{ dbt.type_int() }}) as disch_disposition_cd
  , cast(disch_to_loctn_cd as {{ dbt.type_int() }}) as disch_to_loctn_cd
  , cast(preadmit_nbr as {{ dbt.type_string() }}) as preadmit_nbr
  , cast(place_of_svc_org_id as {{ dbt.type_int() }}) as place_of_svc_org_id
  , cast(place_of_svc_type_cd as {{ dbt.type_int() }}) as place_of_svc_type_cd
  , cast(place_of_svc_admit_dt_tm as {{ dbt.type_timestamp() }}) as place_of_svc_admit_dt_tm
  , cast(kiosk_queue_nbr_dt_tm as {{ dbt.type_timestamp() }}) as kiosk_queue_nbr_dt_tm
  , cast(kiosk_queue_nbr_txt as {{ dbt.type_string() }}) as kiosk_queue_nbr_txt
  , cast(referral_source_cd as {{ dbt.type_int() }}) as referral_source_cd
  , cast(admit_decision_dt_tm as {{ dbt.type_timestamp() }}) as admit_decision_dt_tm
  , cast(admit_early_ind as {{ dbt.type_int() }}) as admit_early_ind
  , cast(treatment_phase_cd as {{ dbt.type_int() }}) as treatment_phase_cd
  , cast(accident_related_ind as {{ dbt.type_int() }}) as accident_related_ind
  , cast(order_source_cd as {{ dbt.type_int() }}) as order_source_cd
  , cast(payment_collection_status_cd as {{ dbt.type_int() }}) as payment_collection_status_cd
  , cast(disch_prsnl_id as {{ dbt.type_int() }}) as disch_prsnl_id
from {{ source('cerner', 'encounter') }}
where active_ind = 1
and end_effective_dt_tm > {{ dbt.current_timestamp() }}
