select
    cast(race_cd as {{ dbt.type_int() }}) as race_cd
    , cast(religion_cd as {{ dbt.type_int() }}) as religion_cd
    , cast(sex_cd as {{ dbt.type_int() }}) as sex_cd
    , cast(sex_age_change_ind as {{ dbt.type_int() }}) as sex_age_change_ind
    , cast(data_status_cd as {{ dbt.type_int() }}) as data_status_cd
    , cast(data_status_dt_tm as {{ dbt.type_timestamp() }}) as data_status_dt_tm
    , cast(data_status_prsnl_id as {{ dbt.type_int() }}) as data_status_prsnl_id
    , cast(contributor_system_cd as {{ dbt.type_int() }}) as contributor_system_cd
    , cast(language_dialect_cd as {{ dbt.type_int() }}) as language_dialect_cd
    , cast(name_last as {{ dbt.type_string() }}) as name_last
    , cast(name_first as {{ dbt.type_string() }}) as name_first
    , cast(name_phonetic as {{ dbt.type_string() }}) as name_phonetic
    , cast(last_encntr_dt_tm as {{ dbt.type_timestamp() }}) as last_encntr_dt_tm
    , cast(species_cd as {{ dbt.type_int() }}) as species_cd
    , cast(confid_level_cd as {{ dbt.type_int() }}) as confid_level_cd
    , cast(vip_cd as {{ dbt.type_int() }}) as vip_cd
    , cast(name_first_synonym_id as {{ dbt.type_int() }}) as name_first_synonym_id
    , cast(citizenship_cd as {{ dbt.type_int() }}) as citizenship_cd
    , cast(vet_military_status_cd as {{ dbt.type_int() }}) as vet_military_status_cd
    , cast(mother_maiden_name as {{ dbt.type_string() }}) as mother_maiden_name
    , cast(nationality_cd as {{ dbt.type_int() }}) as nationality_cd
    , cast(ft_entity_name as {{ dbt.type_string() }}) as ft_entity_name
    , cast(ft_entity_id as {{ dbt.type_int() }}) as ft_entity_id
    , cast(name_middle_key as {{ dbt.type_string() }}) as name_middle_key
    , cast(name_middle as {{ dbt.type_string() }}) as name_middle
    , cast(name_first_phonetic as {{ dbt.type_string() }}) as name_first_phonetic
    , cast(name_last_phonetic as {{ dbt.type_string() }}) as name_last_phonetic
    , cast(name_last_key_nls as {{ dbt.type_string() }}) as name_last_key_nls
    , cast(name_first_key_nls as {{ dbt.type_string() }}) as name_first_key_nls
    , cast(name_middle_key_nls as {{ dbt.type_string() }}) as name_middle_key_nls
    , cast(military_rank_cd as {{ dbt.type_int() }}) as military_rank_cd
    , cast(military_base_location as {{ dbt.type_string() }}) as military_base_location
    , cast(military_service_cd as {{ dbt.type_int() }}) as military_service_cd
    , cast(deceased_source_cd as {{ dbt.type_int() }}) as deceased_source_cd
    , cast(cause_of_death_cd as {{ dbt.type_int() }}) as cause_of_death_cd
    , cast(birth_prec_flag as {{ dbt.type_int() }}) as birth_prec_flag
    , cast(abs_birth_dt_tm as {{ dbt.type_timestamp() }}) as abs_birth_dt_tm
    , cast(archive_env_id as {{ dbt.type_int() }}) as archive_env_id
    , cast(archive_status_cd as {{ dbt.type_int() }}) as archive_status_cd
    , cast(archive_status_dt_tm as {{ dbt.type_timestamp() }}) as archive_status_dt_tm
    , cast(last_accessed_dt_tm as {{ dbt.type_timestamp() }}) as last_accessed_dt_tm
    , cast(next_restore_dt_tm as {{ dbt.type_timestamp() }}) as next_restore_dt_tm
    , cast(age_at_death as {{ dbt.type_int() }}) as age_at_death
    , cast(age_at_death_unit_cd as {{ dbt.type_int() }}) as age_at_death_unit_cd
    , cast(age_at_death_prec_mod_flag as {{ dbt.type_int() }}) as age_at_death_prec_mod_flag
    , cast(deceased_dt_tm_prec_flag as {{ dbt.type_int() }}) as deceased_dt_tm_prec_flag
    , cast(logical_domain_id as {{ dbt.type_int() }}) as logical_domain_id
    , cast(deceased_id_method_cd as {{ dbt.type_int() }}) as deceased_id_method_cd
    , cast(name_middle_key_a_nls as {{ dbt.type_string() }}) as name_middle_key_a_nls
    , cast(name_last_key_a_nls as {{ dbt.type_string() }}) as name_last_key_a_nls
    , cast(name_first_key_a_nls as {{ dbt.type_string() }}) as name_first_key_a_nls
    , cast(person_status_cd as {{ dbt.type_int() }}) as person_status_cd
    , cast(person_id as {{ dbt.type_int() }}) as person_id
    , cast(updt_cnt as {{ dbt.type_int() }}) as updt_cnt
    , cast(updt_dt_tm as {{ dbt.type_timestamp() }}) as updt_dt_tm
    , cast(updt_id as {{ dbt.type_int() }}) as updt_id
    , cast(updt_task as {{ dbt.type_int() }}) as updt_task
    , cast(updt_applctx as {{ dbt.type_int() }}) as updt_applctx
    , cast(active_ind as {{ dbt.type_int() }}) as active_ind
    , cast(active_status_cd as {{ dbt.type_int() }}) as active_status_cd
    , cast(active_status_prsnl_id as {{ dbt.type_int() }}) as active_status_prsnl_id
    , cast(active_status_dt_tm as {{ dbt.type_timestamp() }}) as active_status_dt_tm
    , cast(create_dt_tm as {{ dbt.type_timestamp() }}) as create_dt_tm
    , cast(create_prsnl_id as {{ dbt.type_int() }}) as create_prsnl_id
    , cast(beg_effective_dt_tm as {{ dbt.type_timestamp() }}) as beg_effective_dt_tm
    , cast(end_effective_dt_tm as {{ dbt.type_timestamp() }}) as end_effective_dt_tm
    , cast(person_type_cd as {{ dbt.type_int() }}) as person_type_cd
    , cast(name_last_key as {{ dbt.type_string() }}) as name_last_key
    , cast(name_first_key as {{ dbt.type_string() }}) as name_first_key
    , cast(name_full_formatted as {{ dbt.type_string() }}) as name_full_formatted
    , cast(autopsy_cd as {{ dbt.type_int() }}) as autopsy_cd
    , cast(birth_dt_cd as {{ dbt.type_int() }}) as birth_dt_cd
    , cast(birth_dt_tm as {{ dbt.type_timestamp() }}) as birth_dt_tm
    , cast(conception_dt_tm as {{ dbt.type_timestamp() }}) as conception_dt_tm
    , cast(cause_of_death as {{ dbt.type_string() }}) as cause_of_death
    , cast(deceased_cd as {{ dbt.type_int() }}) as deceased_cd
    , cast(deceased_dt_tm as {{ dbt.type_timestamp() }}) as deceased_dt_tm
    , cast(ethnic_grp_cd as {{ dbt.type_int() }}) as ethnic_grp_cd
    , cast(language_cd as {{ dbt.type_int() }}) as ethnic_grp_cd
    , cast(marital_type_cd as {{ dbt.type_int() }}) as marital_type_cd
    , cast(purge_option_cd as {{ dbt.type_int() }}) as purge_option_cd
    , cast(birth_tz_name as {{ dbt.type_string() }}) as birth_tz_name
    , cast(deceased_tz_name as {{ dbt.type_string() }}) as deceased_tz_name
from {{ source('cerner_raw', 'person') }}
where active_ind = 1
and end_effective_dt_tm > current_timestamp()
