select    
    cast(order_schedule_precision_bit as {{ dbt.type_int() }}) as order_schedule_precision_bit
    , cast(future_location_facility_cd as {{ dbt.type_int() }}) as future_location_facility_cd
    , cast(future_location_nurse_unit_cd as {{ dbt.type_int() }}) as future_location_nurse_unit_cd
    , cast(protocol_order_id as {{ dbt.type_int() }}) as protocol_order_id
    , cast(prescription_group_value as {{ dbt.type_int() }}) as prescription_group_value
    , cast(day_of_treatment_sequence as {{ dbt.type_int() }}) as day_of_treatment_sequence
    , cast(formulary_status_cd as {{ dbt.type_int() }}) as formulary_status_cd
    , cast(dosing_method_flag as {{ dbt.type_int() }}) as dosing_method_flag
    , cast(warning_level_bit as {{ dbt.type_int() }}) as warning_level_bit
    , cast(template_dose_sequence as {{ dbt.type_int() }}) as template_dose_sequence
    , cast(latest_communication_type_cd as {{ dbt.type_int() }}) as latest_communication_type_cd
    , cast(order_id as {{ dbt.type_int() }}) as order_id
    , cast(oe_format_id as {{ dbt.type_int() }}) as oe_format_id
    , cast(encntr_id as {{ dbt.type_int() }}) as encntr_id
    , cast(person_id as {{ dbt.type_int() }}) as person_id
    , cast(catalog_cd as {{ dbt.type_int() }}) as catalog_cd
    , cast(suspend_ind as {{ dbt.type_int() }}) as suspend_ind
    , cast(contributor_system_cd as {{ dbt.type_int() }}) as contributor_system_cd
    , cast(catalog_type_cd as {{ dbt.type_int() }}) as catalog_type_cd
    , cast(orig_order_dt_tm as {{ dbt.type_timestamp() }}) as orig_order_dt_tm
    , cast(order_status_cd as {{ dbt.type_int() }}) as order_status_cd
    , cast(order_mnemonic as {{ dbt.type_string() }}) as order_mnemonic
    , cast(last_action_sequence as {{ dbt.type_int() }}) as last_action_sequence
    , cast(last_update_provider_id as {{ dbt.type_int() }}) as last_update_provider_id
    , cast(activity_type_cd as {{ dbt.type_int() }}) as activity_type_cd
    , cast(order_detail_display_line as {{ dbt.type_string() }}) as order_detail_display_line
    , cast(template_order_id as {{ dbt.type_int() }}) as template_order_id
    , cast(template_order_flag as {{ dbt.type_int() }}) as template_order_flag
    , cast(synonym_id as {{ dbt.type_int() }}) as synonym_id
    , cast(link_order_flag as {{ dbt.type_int() }}) as link_order_flag
    , cast(link_order_id as {{ dbt.type_int() }}) as link_order_id
    , cast(group_order_id as {{ dbt.type_int() }}) as group_order_id
    , cast(group_order_flag as {{ dbt.type_int() }}) as group_order_flag
    , cast(status_dt_tm as {{ dbt.type_timestamp() }}) as status_dt_tm
    , cast(status_prsnl_id as {{ dbt.type_int() }}) as status_prsnl_id
    , cast(iv_ind as {{ dbt.type_int() }}) as iv_ind
    , cast(constant_ind as {{ dbt.type_int() }}) as constant_ind
    , cast(prn_ind as {{ dbt.type_int() }}) as prn_ind
    , cast(order_comment_ind as {{ dbt.type_int() }}) as order_comment_ind
    , cast(need_rx_verify_ind as {{ dbt.type_int() }}) as need_rx_verify_ind
    , cast(need_nurse_review_ind as {{ dbt.type_int() }}) as need_nurse_review_ind
    , cast(need_doctor_cosign_ind as {{ dbt.type_int() }}) as need_doctor_cosign_ind
    , cast(current_start_dt_tm as {{ dbt.type_timestamp() }}) as current_start_dt_tm
    , cast(projected_stop_dt_tm as {{ dbt.type_timestamp() }}) as projected_stop_dt_tm
    , cast(updt_dt_tm as {{ dbt.type_timestamp() }}) as updt_dt_tm
    , cast(updt_id as {{ dbt.type_int() }}) as updt_id
    , cast(updt_task as {{ dbt.type_int() }}) as updt_task
    , cast(updt_cnt as {{ dbt.type_int() }}) as updt_cnt
    , cast(updt_applctx as {{ dbt.type_int() }}) as updt_applctx
    , cast(encntr_financial_id as {{ dbt.type_int() }}) as encntr_financial_id
    , cast(suspend_effective_dt_tm as {{ dbt.type_timestamp() }}) as suspend_effective_dt_tm
    , cast(resume_ind as {{ dbt.type_int() }}) as resume_ind
    , cast(resume_effective_dt_tm as {{ dbt.type_timestamp() }}) as resume_effective_dt_tm
    , cast(discontinue_ind as {{ dbt.type_int() }}) as discontinue_ind
    , cast(discontinue_effective_dt_tm as {{ dbt.type_timestamp() }}) as discontinue_effective_dt_tm
    , cast(product_id as {{ dbt.type_int() }}) as product_id
    , cast(cs_order_id as {{ dbt.type_int() }}) as cs_order_id
    , cast(cs_flag as {{ dbt.type_int() }}) as cs_flag
    , cast(active_status_cd as {{ dbt.type_int() }}) as active_status_cd
    , cast(active_status_dt_tm as {{ dbt.type_timestamp() }}) as active_status_dt_tm
    , cast(active_status_prsnl_id as {{ dbt.type_int() }}) as active_status_prsnl_id
    , cast(active_ind as {{ dbt.type_int() }}) as active_ind
    , cast(hna_order_mnemonic as {{ dbt.type_string() }}) as hna_order_mnemonic
    , cast(orig_ord_as_flag as {{ dbt.type_int() }}) as orig_ord_as_flag
    , cast(ingredient_ind as {{ dbt.type_int() }}) as ingredient_ind
    , cast(dept_status_cd as {{ dbt.type_int() }}) as dept_status_cd
    , cast(ref_text_mask as {{ dbt.type_int() }}) as ref_text_mask
    , cast(clinical_display_line as {{ dbt.type_string() }}) as clinical_display_line
    , cast(interest_dt_tm as {{ dbt.type_timestamp() }}) as interest_dt_tm
    , cast(discontinue_type_cd as {{ dbt.type_int() }}) as discontinue_type_cd
    , cast(rx_mask as {{ dbt.type_int() }}) as rx_mask
    , cast(sch_state_cd as {{ dbt.type_int() }}) as sch_state_cd
    , cast(orig_order_convs_seq as {{ dbt.type_int() }}) as orig_order_convs_seq
    , cast(dcp_clin_cat_cd as {{ dbt.type_int() }}) as dcp_clin_cat_cd
    , cast(dept_misc_line as {{ dbt.type_string() }}) as dept_misc_line
    , cast(hide_flag as {{ dbt.type_int() }}) as hide_flag
    , cast(interval_ind as {{ dbt.type_int() }}) as interval_ind
    , cast(orderable_type_flag as {{ dbt.type_int() }}) as orderable_type_flag
    , cast(cki as {{ dbt.type_string() }}) as cki
    , cast(need_physician_validate_ind as {{ dbt.type_int() }}) as need_physician_validate_ind
    , cast(med_order_type_cd as {{ dbt.type_int() }}) as med_order_type_cd
    , cast(soft_stop_dt_tm as {{ dbt.type_timestamp() }}) as soft_stop_dt_tm
    , cast(ordered_as_mnemonic as {{ dbt.type_string() }}) as ordered_as_mnemonic
    , cast(incomplete_order_ind as {{ dbt.type_int() }}) as incomplete_order_ind
    , cast(last_ingred_action_sequence as {{ dbt.type_int() }}) as last_ingred_action_sequence
    , cast(stop_type_cd as {{ dbt.type_int() }}) as stop_type_cd
    , cast(template_core_action_sequence as {{ dbt.type_int() }}) as template_core_action_sequence
    , cast(eso_new_order_ind as {{ dbt.type_int() }}) as eso_new_order_ind
    , cast(frequency_id as {{ dbt.type_int() }}) as frequency_id
    , cast(freq_type_flag as {{ dbt.type_int() }}) as freq_type_flag
    , cast(last_core_action_sequence as {{ dbt.type_int() }}) as last_core_action_sequence
    , cast(modified_start_dt_tm as {{ dbt.type_timestamp() }}) as modified_start_dt_tm
    , cast(comment_type_mask as {{ dbt.type_int() }}) as comment_type_mask
    , cast(override_flag as {{ dbt.type_int() }}) as override_flag
    , cast(remaining_dose_cnt as {{ dbt.type_int() }}) as remaining_dose_cnt
    , cast(valid_dose_dt_tm as {{ dbt.type_timestamp() }}) as valid_dose_dt_tm
    , cast(link_type_flag as {{ dbt.type_int() }}) as link_type_flag
    , cast(link_nbr as {{ dbt.type_int() }}) as link_nbr
    , cast(ad_hoc_order_flag as {{ dbt.type_int() }}) as ad_hoc_order_flag
    , cast(pathway_catalog_id as {{ dbt.type_int() }}) as pathway_catalog_id
    , cast(simplified_display_line as {{ dbt.type_string() }}) as simplified_display_line
    , cast(prescription_order_id as {{ dbt.type_int() }}) as prescription_order_id
    , cast(source_cd as {{ dbt.type_int() }}) as source_cd
    , cast(need_rx_clin_review_flag as {{ dbt.type_int() }}) as need_rx_clin_review_flag
    , cast(clin_relevant_updt_dt_tm as {{ dbt.type_timestamp() }}) as clin_relevant_updt_dt_tm
    , cast(iv_set_synonym_id as {{ dbt.type_int() }}) as iv_set_synonym_id
    , cast(soft_stop_tz_name as {{ dbt.type_string() }}) as soft_stop_tz_name
    , cast(projected_stop_tz_name as {{ dbt.type_string() }}) as projected_stop_tz_name
    , cast(resume_effective_tz_name as {{ dbt.type_string() }}) as resume_effective_tz_name
    , cast(discontinue_effective_tz_name as {{ dbt.type_string() }}) as discontinue_effective_tz_name
    , cast(orig_order_tz_name as {{ dbt.type_string() }}) as orig_order_tz_name
    , cast(suspend_effective_tz_name as {{ dbt.type_string() }}) as suspend_effective_tz_name
    , cast(current_start_tz_name as {{ dbt.type_string() }}) as current_start_tz_name
    , cast(clin_relevant_updt_tz_name as {{ dbt.type_string() }}) as clin_relevant_updt_tz_name
    , cast(originating_encntr_id as {{ dbt.type_int() }}) as originating_encntr_id
from {{ source('cerner_raw', 'orders') }}
where active_ind = 1
and end_effective_dt_tm > current_timestamp()
