select
      cast(family_nbr_of_minors_cnt as {{ dbt.type_int() }}) as family_nbr_of_minors_cnt
    , cast(source_sync_level_flag as {{ dbt.type_int() }}) as source_sync_level_flag
    , cast(iqh_participant_cd as {{ dbt.type_int() }}) as iqh_participant_cd
    , cast(church_cd as {{ dbt.type_int() }}) as church_cd
    , cast(credit_hrs_taking as {{ dbt.type_int() }}) as credit_hrs_taking
    , cast(cumm_leave_days as {{ dbt.type_int() }}) as cumm_leave_days
    , cast(current_balance as {{ dbt.type_float() }}) as current_balance
    , cast(current_grade as {{ dbt.type_int() }}) as current_grade
    , cast(custody_cd as {{ dbt.type_int() }}) as custody_cd
    , cast(degree_complete_cd as {{ dbt.type_int() }}) as degree_complete_cd
    , cast(diet_type_cd as {{ dbt.type_int() }}) as diet_type_cd
    , cast(family_income as {{ dbt.type_float() }}) as family_income
    , cast(family_size as {{ dbt.type_int() }}) as family_size
    , cast(highest_grade_complete_cd as {{ dbt.type_int() }}) as highest_grade_complete_cd
    , cast(immun_on_file_cd as {{ dbt.type_int() }}) as immun_on_file_cd
    , cast(interp_required_cd as {{ dbt.type_int() }}) as interp_required_cd
    , cast(interp_type_cd as {{ dbt.type_int() }}) as interp_type_cd
    , cast(microfilm_cd as {{ dbt.type_int() }}) as microfilm_cd
    , cast(nbr_of_brothers as {{ dbt.type_int() }}) as nbr_of_brothers
    , cast(nbr_of_sisters as {{ dbt.type_int() }}) as nbr_of_sisters
    , cast(organ_donor_cd as {{ dbt.type_int() }}) as organ_donor_cd
    , cast(parent_marital_status_cd as {{ dbt.type_int() }}) as parent_marital_status_cd
    , cast(smokes_cd as {{ dbt.type_int() }}) as smokes_cd
    , cast(tumor_registry_cd as {{ dbt.type_int() }}) as tumor_registry_cd
    , cast(last_bill_dt_tm as {{ dbt.type_timestamp() }}) as last_bill_dt_tm
    , cast(last_bind_dt_tm as {{ dbt.type_timestamp() }}) as last_bind_dt_tm
    , cast(last_discharge_dt_tm as {{ dbt.type_timestamp() }}) as last_discharge_dt_tm
    , cast(last_event_updt_dt_tm as {{ dbt.type_timestamp() }}) as last_event_updt_dt_tm
    , cast(last_payment_dt_tm as {{ dbt.type_timestamp() }}) as last_payment_dt_tm
    , cast(last_atd_activity_dt_tm as {{ dbt.type_timestamp() }}) as last_atd_activity_dt_tm
    , cast(data_status_cd as {{ dbt.type_int() }}) as data_status_cd
    , cast(data_status_dt_tm as {{ dbt.type_timestamp() }}) as data_status_dt_tm
    , cast(data_status_prsnl_id as {{ dbt.type_int() }}) as data_status_prsnl_id
    , cast(contributor_system_cd as {{ dbt.type_int() }}) as contributor_system_cd
    , cast(student_cd as {{ dbt.type_int() }}) as student_cd
    , cast(living_dependency_cd as {{ dbt.type_int() }}) as living_dependency_cd
    , cast(living_arrangement_cd as {{ dbt.type_int() }}) as living_arrangement_cd
    , cast(living_will_cd as {{ dbt.type_int() }}) as living_will_cd
    , cast(nbr_of_pregnancies as {{ dbt.type_int() }}) as nbr_of_pregnancies
    , cast(last_trauma_dt_tm as {{ dbt.type_timestamp() }}) as last_trauma_dt_tm
    , cast(mother_identifier as {{ dbt.type_string() }}) as mother_identifier
    , cast(mother_identifier_cd as {{ dbt.type_int() }}) as mother_identifier_cd
    , cast(disease_alert_cd as {{ dbt.type_int() }}) as disease_alert_cd
    , cast(process_alert_cd as {{ dbt.type_int() }}) as process_alert_cd
    , cast(contact_list_cd as {{ dbt.type_int() }}) as contact_list_cd
    , cast(gest_age_at_birth as {{ dbt.type_int() }}) as gest_age_at_birth
    , cast(gest_age_method_cd as {{ dbt.type_int() }}) as gest_age_method_cd
    , cast(contact_time as {{ dbt.type_string() }}) as contact_time
    , cast(contact_method_cd as {{ dbt.type_int() }}) as contact_method_cd
    , cast(callback_consent_cd as {{ dbt.type_int() }}) as callback_consent_cd
    , cast(written_format_cd as {{ dbt.type_int() }}) as written_format_cd
    , cast(prev_contact_ind as {{ dbt.type_int() }}) as prev_contact_ind
    , cast(birth_order_cd as {{ dbt.type_int() }}) as birth_order_cd
    , cast(source_version_number as {{ dbt.type_string() }}) as source_version_number
    , cast(source_last_sync_dt_tm as {{ dbt.type_timestamp() }}) as source_last_sync_dt_tm
    , cast(person_id as {{ dbt.type_int() }}) as person_id
    , cast(updt_cnt as {{ dbt.type_int() }}) as updt_cnt
    , cast(updt_dt_tm as {{ dbt.type_timestamp() }}) as 
    , cast(updt_id as {{ dbt.type_int() }}) as updt_id
    , cast(updt_task as {{ dbt.type_int() }}) as updt_task
    , cast(updt_applctx as {{ dbt.type_int() }}) as updt_applctx
    , cast(active_ind as {{ dbt.type_int() }}) as active_ind
    , cast(active_status_cd as {{ dbt.type_int() }}) as active_status_cd
    , cast(active_status_dt_tm as {{ dbt.type_timestamp() }}) as active_status_dt_tm
    , cast(active_status_prsnl_id as {{ dbt.type_int() }}) as active_status_prsnl_id
    , cast(beg_effective_dt_tm as {{ dbt.type_timestamp() }}) as beg_effective_dt_tm
    , cast(end_effective_dt_tm as {{ dbt.type_timestamp() }}) as end_effective_dt_tm
    , cast(adopted_cd as {{ dbt.type_int() }}) as adopted_cd
    , cast(bad_debt_cd as {{ dbt.type_int() }}) as bad_debt_cd
    , cast(baptised_cd as {{ dbt.type_int() }}) as baptised_cd
    , cast(birth_multiple_cd as {{ dbt.type_int() }}) as birth_multiple_cd
    , cast(birth_order as {{ dbt.type_int() }}) as birth_order
    , cast(birth_length as {{ dbt.type_float() }}) as birth_length
    , cast(birth_length_units_cd as {{ dbt.type_int() }}) as birth_length_units_cd
    , cast(birth_name as {{ dbt.type_string() }}) as birth_name
    , cast(birth_weight as {{ dbt.type_float() }}) as birth_weight
    , cast(birth_weight_units_cd as {{ dbt.type_int() }}) as birth_weight_units_cd
from {{ source('cerner_raw', 'person_patient') }}
where active_ind = 1
and end_effective_dt_tm > current_timestamp()
