select
 cast(current_start_dt_tm as {{ dbt.type_timestamp() }}) as 
, cast(source_dot_order_id as {{ dbt.type_int() }}) as 
, cast(source_dot_action_seq as {{ dbt.type_int() }}) as 
, cast(source_protocol_action_seq as {{ dbt.type_int() }}) as 
, cast(formulary_status_cd as {{ dbt.type_int() }}) as 
, cast(order_schedule_precision_bit as {{ dbt.type_int() }}) as 
, cast(billing_provider_flag as {{ dbt.type_int() }}) as 
, cast(valid_dose_dt_tm as {{ dbt.type_timestamp() }}) as 
, cast(order_id as {{ dbt.type_int() }}) as 
, cast(action_sequence as {{ dbt.type_int() }}) as 
, cast(communication_type_cd as {{ dbt.type_int() }}) as 
, cast(action_rejected_ind as {{ dbt.type_int() }}) as 
, cast(order_conversation_id as {{ dbt.type_int() }}) as 
, cast(contributor_system_cd as {{ dbt.type_int() }}) as 
, cast(order_convs_seq as {{ dbt.type_int() }}) as 
, cast(order_locn_cd as {{ dbt.type_int() }}) as 
, cast(action_type_cd as {{ dbt.type_int() }}) as 
, cast(order_dt_tm as {{ dbt.type_timestamp() }}) as 
, cast(action_dt_tm as {{ dbt.type_timestamp() }}) as 
, cast(action_personnel_id as {{ dbt.type_int() }}) as 
, cast(effective_dt_tm as {{ dbt.type_timestamp() }}) as 
, cast(order_provider_id as {{ dbt.type_int() }}) as 
, cast(incomplete_order_ind as {{ dbt.type_int() }}) as 
, cast(updt_applctx as {{ dbt.type_int() }}) as 
, cast(updt_dt_tm as {{ dbt.type_timestamp() }}) as 
, cast(updt_id as {{ dbt.type_int() }}) as 
, cast(updt_task as {{ dbt.type_int() }}) as 
, cast(updt_cnt as {{ dbt.type_int() }}) as 
, cast(order_app_nbr as {{ dbt.type_int() }}) as 
, cast(order_action_id as {{ dbt.type_int() }}) as 
, cast(needs_verify_ind as {{ dbt.type_int() }}) as 
, cast(inactive_flag as {{ dbt.type_int() }}) as 
, cast(order_status_cd as {{ dbt.type_int() }}) as 
, cast(dept_status_cd as {{ dbt.type_int() }}) as 
, cast(sch_state_cd as {{ dbt.type_int() }}) as 
, cast(undo_action_type_cd as {{ dbt.type_int() }}) as 
, cast(clinical_display_line as {{ dbt.type_string() }}) as 
, cast(eso_action_cd as {{ dbt.type_int() }}) as 
, cast(medstudent_action_ind as {{ dbt.type_int() }}) as 
, cast(order_detail_display_line as {{ dbt.type_string() }}) as 
, cast(core_ind as {{ dbt.type_int() }}) as 
, cast(constant_ind as {{ dbt.type_int() }}) as 
, cast(frequency_id as {{ dbt.type_int() }}) as 
, cast(stop_type_cd as {{ dbt.type_int() }}) as 
, cast(template_order_flag as {{ dbt.type_int() }}) as 
, cast(prn_ind as {{ dbt.type_int() }}) as 
, cast(supervising_provider_id as {{ dbt.type_int() }}) as 
, cast(digital_signature_ident as {{ dbt.type_string() }}) as 
, cast(projected_stop_dt_tm as {{ dbt.type_timestamp() }}) as 
, cast(simplified_display_line as {{ dbt.type_string() }}) as 
, cast(need_clin_review_flag as {{ dbt.type_int() }}) as 
, cast(action_qualifier_cd as {{ dbt.type_int() }}) as 
, cast(action_initiated_dt_tm as {{ dbt.type_timestamp() }}) as 
, cast(next_dose_dt_tm as {{ dbt.type_timestamp() }}) as 
, cast(current_start_tz_name as {{ dbt.type_string() }}) as 
, cast(order_tz_name as {{ dbt.type_string() }}) as 
, cast(effective_tz_name as {{ dbt.type_string() }}) as 
, cast(action_tz_name as {{ dbt.type_string() }}) as 
, cast(projected_stop_tz_name as {{ dbt.type_string() }}) as 
from {{ ref('cerner_raw', 'order_action') }}
