select
    cast(event_cd_disp as {{ dbt.type_string() }}) as event_cd_disp,
    cast(event_cd_disp_key as {{ dbt.type_string() }}) as event_cd_disp_key,
    cast(code_status_cd as {{ dbt.type_int() }}) as code_status_cd,
    cast(def_docmnt_attributes as {{ dbt.type_string() }}) as def_docmnt_attributes,
    cast(def_docmnt_format_cd as {{ dbt.type_int() }}) as def_docmnt_format_cd,
    cast(def_docmnt_storage_cd as {{ dbt.type_int() }}) as def_docmnt_storage_cd,
    cast(def_event_class_cd as {{ dbt.type_int() }}) as def_event_class_cd,
    cast(def_event_confid_level_cd as {{ dbt.type_int() }}) as def_event_confid_level_cd,
    cast(def_event_level as {{ dbt.type_int() }}) as def_event_level,
    cast(event_add_access_ind as {{ dbt.type_int() }}) as event_add_access_ind,
    cast(event_cd_subclass_cd as {{ dbt.type_int() }}) as event_cd_subclass_cd,
    cast(event_chg_access_ind as {{ dbt.type_int() }}) as event_chg_access_ind,
    cast(event_set_name as {{ dbt.type_string() }}) as event_set_name,
    cast(retention_days as {{ dbt.type_int() }}) as retention_days,
    cast(updt_applctx as {{ dbt.type_int() }}) as updt_applctx,
    cast(updt_cnt as {{ dbt.type_int() }}) as updt_cnt,
    cast(updt_dt_tm as {{ dbt.type_timestamp() }}) as updt_dt_tm,
    cast(updt_id as {{ dbt.type_int() }}) as updt_id,
    cast(updt_task as {{ dbt.type_int() }}) as updt_task,
    cast(event_code_status_cd as {{ dbt.type_int() }}) as event_code_status_cd,
    cast(collating_seq as {{ dbt.type_int() }}) as collating_seq,
    cast(event_cd as {{ dbt.type_int() }}) as event_cd,
    cast(event_cd_definition as {{ dbt.type_string() }}) as event_cd_definition,
    cast(event_cd_descr as {{ dbt.type_string() }}) as event_cd_descr
from {{ ref('cerner_raw', 'v500_event_code') }}
